version: 2
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Build the REDCap image
          command: |
              cd rdc
              set -x
              docker-compose up -d

workflows:
  version: 2
  build:
    jobs:
      - test              