version: 2
jobs:
  test:
    machine: true
    working_directory: /redcap-docker-compose/rdc/
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: Build the REDCap image
          command: |
              set -x
              docker-compose up -d

workflows:
  version: 2
  build:
    jobs:
      - test              