version: '3'
services:
  web:
    build: docker-web
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ${WEB_OVERRIDES}:/etc/container-config-override
      - ${WEBROOT_DIR}:/var/www/html
      - ${LOGS_DIR}:/var/log/apache2
# You can prevent your REDCap from accessing certain sites (like twilio) using these settings
#    extra_hosts:
#      - "api.twilio.com:127.0.0.1"
#      - "www.twilio.com:127.0.0.1"
#      - "taskrouter.twilio.com:127.0.0.1"
#      - "lookups.twilio.com:127.0.0.1"
#      - "event-bridge.twilio.com:127.0.0.1"

  db:
    image: mysql:5.7
    env_file: .env
    restart: always
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
      - ${LOGS_DIR}:/var/log/mysql
      - ${MYSQL_OVERRIDES}:/etc/mysql/mysql.conf.d
    ports:
     - "${MYSQL_PORT}:3306"

  cron:
    build: docker-cron
    restart: always
    env_file: .env
    depends_on:
      - web
      - db
    volumes:
      - ${CRON_LOGROTATE_DIR}:/etc/logrotate.d
      - ${LOGS_DIR}:/logs-dir

  mailhog:
    build: docker-mailhog
    restart: always
    env_file: .env
    depends_on:
      - web
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - ${MAILHOG_DIR}:/maildir
      - ${MAILHOG_OUTGOING_SMTP_FILE}:/outgoing_smtp.json
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /maildir
      MH_OUTGOING_SMTP: /outgoing_smtp.json
      MH_UI_WEB_PATH: mailhog

  # THIS CONTAINER IS OPTIONAL IF YOU WANT TO HAVE PHPMYADMIN - OTHERWISE COMMENT IT OUT
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    env_file: .env
#    depends_on:
#      - web
#      - db
#    restart: always
#    ports:
#      - "${PHPMYADMIN_PORT}:80"

volumes:
  mysql-volume:
  logs-volume:
  mailhog-volume:
